language: go

go:
  - 1.5.4
  - 1.6.3
  - 1.7.3
  - master

sudo: false

cache:
  directories:
    - ./vendor

before_install:
  - sudo add-apt-repository ppa:masterminds/glide
  - sudo apt-get update
  - sudo apt-get install glide

install:
  - glide i

script:
  - go test ./...
