language: go

go:
  - 1.6.3
  - 1.7.3
  - master

sudo: required

cache:
  directories:
    - ./vendor

before_install:
  - yes | sudo add-apt-repository ppa:masterminds/glide
  - sudo apt-get update
  - sudo apt-get install glide

script:
  - glide i
  - make test-cover

after_success:
  - bash <(curl -s https://codecov.io/bash)
